/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js type tooling in normal projects and is
// kept checked in here so a fresh clone type-checks before the first dev run.
